name: Build Kernel

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/kho447520-jpg/android_kernel_samsung_seraphine
          kernel-branch: android-4.9-q
          config: itzkaguya-perf_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: false
          android-version: 10
          anykernel3: true
          release: true
          disable-lto: true
          extra-make-args: 'KCFLAGS="-Wno-error=maybe-uninitialized -Wno-error"'
          access-token: ${{ secrets.GITHUB_TOKEN }}
